create database Car_service;
use Car_service;

select * from Region;
desc region;

#REGION TABLE 
CREATE TABLE REGION(
REGION_ID INT PRIMARY KEY,
REGION_NAME VARCHAR(50),
STATE VARCHAR(50)
);

#AREA TABLE
CREATE TABLE AREA(
AREA_ID VARCHAR(10),
REGION_ID INT,
AREA_NAME VARCHAR(255),
CONSTRAINT AREA_ID_PK PRIMARY KEY (AREA_ID),
CONSTRAINT AREA_REGION_FK FOREIGN KEY (REGION_ID) REFERENCES REGION(REGION_ID)
);


#DRIVER 
CREATE TABLE DRIVER(
DRIVER_ID VARCHAR(10),
DRIVER_NAME VARCHAR(255),
PHONE_NUMBER BIGINT,
COVID_VACCINATION CHAR(4) CHECK(COVID_VACCINATION ="YES" OR COVID_VACCINATION ="NO"  ),
DRIVING_LICENSE CHAR(4) CHECK(DRIVING_LICENSE ="YES" OR DRIVING_LICENSE ="NO"  ),
CONSTRAINT DRIVER_ID_PK PRIMARY KEY (DRIVER_ID)
);

#CABS
CREATE TABLE CABS(
CAB_ID VARCHAR(10),
DRIVER_ID VARCHAR(10),
AREA_ID VARCHAR(10),
CAR_TYPE_ID INT,
CONSTRAINT CAB_ID_PK PRIMARY KEY(CAB_ID),
CONSTRAINT AREA_ID_FK FOREIGN KEY (AREA_ID) REFERENCES  AREA(AREA_ID),
CONSTRAINT DRIVER_ID_FK FOREIGN KEY (DRIVER_ID) REFERENCES  DRIVER(DRIVER_ID),
CONSTRAINT CAR_TYPE_FK FOREIGN KEY (CAR_TYPE_ID) REFERENCES  CAR_TYPE(CAR_TYPE_ID)
);

#CAR_TYPE
CREATE TABLE  CAR_TYPE(
CAR_TYPE_ID INT,
CAR_TYPE VARCHAR(255),
CONSTRAINT CAR_TYPE_ID_PK PRIMARY KEY(CAR_TYPE_ID)
);

#CUSTOMER_TABLE
CREATE TABLE CUSTOMER(
	CUST_ID INT AUTO_INCREMENT,
	CUST_NAME VARCHAR(50),
    CAB_ID VARCHAR(10),
    CONSTRAINT CUST_ID_PK PRIMARY KEY(CUST_ID),
    CONSTRAINT CAB_CUST_FK FOREIGN KEY(CAB_ID) REFERENCES CABS(CAB_ID)
    );
    
ALTER TABLE BOOKING DROP FOREIGN KEY CAB_ID_FK;
ALTER TABLE BOOKING DROP COLUMN CAB_ID;
ALTER TABLE BOOKING ADD COLUMN CUST_ID INT;
ALTER TABLE BOOKING ADD CONSTRAINT CUST_ID_FK
FOREIGN KEY(CUST_ID) REFERENCES CUSTOMER(CUST_ID);

ALTER TABLE CUSTOMER DROP FOREIGN KEY CAB_CUST_FK;
DESC CUSTOMER;
ALTER TABLE CUSTOMER DROP COLUMN CAB_ID;

ALTER TABLE BOOKING ADD COLUMN CAB_ID VARCHAR(10);

ALTER TABLE BOOKING ADD CONSTRAINT CAB_ID_FK
FOREIGN KEY(CAB_ID) REFERENCES CABS(CAB_ID);

ALTER TABLE BOOKING MODIFY BOOKING_ID VARCHAR(10);
ALTER TABLE BOOKING MODIFY TRANSACTION_ID VARCHAR(10);
#BOOKING TABLE GOT CREATED USING PYTHON
DESC BOOKING;



set sql_safe_updates = 0;

delete from booking;


DESC BOOKING;

ALTER TABLE BOOKING 
MODIFY RIDE_DATE DATE;

SELECT * FROM CUSTOMER;#4
SELECT * FROM DRIVER;#5
SELECT * FROM CABS;
select * from region;#1
select * from area;#2
select * from CAR_TYPE;#3
SELECT * FROM BOOKING;


insert into booking values('B31','T0045','2022-05-17',1001,'CAB196');
insert into booking values('B32','T0046','2022-05-18',1001,'CAB186');
insert into booking values('B33','T0047','2022-05-19',1002,'CAB187');

INSERT INTO CABS VALUES('CAB196','DR094','AN3',3);
insert into booking values('B34','T0048','2022-05-18',1001,'CAB187');

describe customer;
